Create Xray scan evidence on app version

diff --git a/.github/workflows/create-application-version.yml b/.github/workflows/create-application-version.yml
--- a/.github/workflows/create-application-version.yml
+++ b/.github/workflows/create-application-version.yml
@@ -147,7 +147,7 @@ jobs:
                   SCAN_STATUS=$(cat response.json | jq '.overall.status'| tr -d \")
                   echo "SCAN_STATUS=$SCAN_STATUS"
                   [ "PENDING" == "$SCAN_STATUS" -o "SCANNING" == "$SCAN_STATUS" ] && echo "Scan in progress. Waiting $WAIT_SECONDS seconds..." && sleep "$WAIT_SECONDS" && continue
-                  [ "DONE" == "$SCAN_STATUS" ] && echo "Scan done." && mv response.json "$OUTPUT_FILE_NAME" && break
+                  [ "DONE" == "$SCAN_STATUS" ] && echo "Scan done." && mv response.json "$OUTPUT_FILE_NAME" && echo "Created output file $OUTPUT_FILE_NAME" && break
                   echo "Scan was not successful."
                   exit 1
               done
@@ -155,6 +155,17 @@ jobs:
 
           wait_for_scan "$QUOTEOFDAY_BODY" quoteofday.xray.result.json
           wait_for_scan "$AI_TRANSLATE_BODY" ai-translate.xray.result.json
+
+      - name: Creating evidence for Xray scans
+        run: |
+          set +e
+          APP_VER=${{ steps.create_app_ver.outputs.app_ver }}
+          [ -f quoteofday.xray.result.json ] || echo "Missing quote of the day Xray scan evidence."
+          [ -f quoteofday.xray.result.json ] && jf evd create --release-bundle "$APP_ID" --release-bundle-version "$APP_VER" \
+            --predicate quoteofday.xray.result.json --predicate-type xray --provider-id jfrog
+          [ -f ai-translate.xray.result.json ] || echo "Missing AI translate Xray scan evidence."
+          [ -f ai-translate.xray.result.json ] && jf evd create --release-bundle "$APP_ID" --release-bundle-version "$APP_VER" \
+            --predicate ai-translate.xray.result.json --predicate-type xray --provider-id jfrog
 
       - name: Promote application to DEV
         run: |
