Edit argo cd deployment files after successful release.

diff --git a/.github/workflows/release-application-version.yml b/.github/workflows/release-application-version.yml
--- a/.github/workflows/release-application-version.yml
+++ b/.github/workflows/release-application-version.yml
@@ -68,3 +68,37 @@ jobs:
             curl -s -X POST -H "Authorization: Bearer $JF_ACCESS_TOKEN" -H "Content-Type: application/json" -d "$REQUEST_BODY" "$RELEASE_URL"
             exit 1
           fi
+
+      - name: Update ArgoCD deployment
+        run: |
+          set +e
+          APP_VER=${{ steps.get_app_ver.outputs.app_ver }}
+          URL="$JF_URL/apptrust/api/v1/applications/$APP_ID/versions/$APP_VER/content?include=sources"
+          echo "Requesting: $URL" 
+          STATUS_CODE=$(curl -s -o result.json -w "%{http_code}" -X GET -H "Authorization: Bearer $JF_ACCESS_TOKEN" "URL")
+
+          if [ "$STATUS_CODE" != "200" ]; then
+            echo "Reuquest failed with code $STATUS_CODE"
+            cat result.json
+            exit 1
+          fi
+
+          function editDeployment() {
+            local BUILD_NAME="$1"
+            local BUILD_VER="$2"
+            local DEPLOYMENT_FILE="argocd/manifests/deployment-$BUILD_NAME.yaml"
+            if [ ! -f "$DEPLOYMENT_FILE" ]; then
+              echo "$DEPLOYMENT_FILE doesn't exist. Skipping.
+              return 0
+            fi
+            echo "Replacing version in file $DEPLOYMENT_FILE to $BUILD_VER"
+            sed -i "s|quotopia-prod-docker/${BUILD_NAME}:[0-9]*|quotopia-prod-docker/${BUILD_NAME}:${BUILD_VER}|g" "DEPLOYMENT_FILE"
+          }
+
+          cat result.json | jq -c '.sources[] | {name: .build.name, number: .build.number}' | while read -r build_info; do
+            name=$(echo "$build_info" | jq -r '.name')
+            number=$(echo "$build_info" | jq -r '.number')
+            echo "Found build with name: $name and number: $number"
+            editDeployment "$name" "$number"
+          done
+
